apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-api
  labels:
    app: books-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books-api
  template:
    metadata:
      labels:
        app: books-api
    spec:
      containers:
        - name: books-api
          image: ghcr.io/lotusnh1/django-api:latest
          command: ["/app/entrypoint.sh"]
          ports:
            - containerPort: 8000  # This is the internal container port
          envFrom:
            - configMapRef:
                name: books-api-env
      # Uncomment this section if you're pulling the image from a private registry
      # imagePullSecrets:
      #   - name: ghcr-secret

