# name: Build and Deploy to MicroK8s

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v2

#     - name: Log in to GitHub Container Registry
#       uses: docker/login-action@v2
#       with:
#         registry: ghcr.io
#         username: ${{ github.actor }}
#         password: ${{ secrets.GITHUB_TOKEN }}

#     - name: Build and push Docker image
#       uses: docker/build-push-action@v4
#       with:
#         push: true
#         tags: ghcr.io/${{ github.repository_owner }}/django-api:latest
name: Test, Build and Deploy to MicroK8s

on:
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      # Load environment variables if needed in steps
      DJANGO_SETTINGS_MODULE: books_api.settings
      # You can also load secrets here if needed
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Python dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Load environment variables from .env
      run: |
        echo "Loading .env file..."
        if [ -f .env ]; then
          export $(cat .env | grep -v '^#' | xargs)
        fi

    - name: Run unit tests
      run: |
        source venv/bin/activate
        python manage.py test

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/django-api:latest



